### ISSUE TITLE
`'target' is a required option` Error

### ISSUE THREAD

**Issue by emirotin** [pateketrueke/yrv#12]
I'm relatively new to Svelte v3 (though I've used v2 some time ago) and I'm currently porting an educational app for my students from React to Svelte.

With all the routers I've tried (yours is the 3rd) I've had different issues :)

Not sure if the problem is specifically with the router or Svelte in general, but currently I'm getting `'target' is a required option`
The simplistic repro app: https://codesandbox.io/s/svelte-yrv-issue-zvelg
I've created it by cleaning up my real app so it is possible I've overlooked something but it's so small I think it's actually OK.

**Comment by pateketrueke** [comment]
Sadly not all online REPLs are svelte-friendly, here is your example: https://svelte.dev/repl/c7a88bb217904abd9726c1f65dd3617a?version=3.18.2

I recommend you to stick to the official Svelte REPL in order to avoid compatibility issues, normally if your code is working on the REPL it'll work everywhere.

**Comment by emirotin** [comment]
Codesandbox is a respectable REPL and I think they've worked with Rich on the official Svelte template (but I may be wrong on this).
But you're right, the thing works in the official REPL, now I've also recreated the example locally and it also works just fine.

Thanks for reproducing this, I'll talk to the Svelte and CS teams.

I want to use CS for my workshop because of the obvious conveniences, hope they can figure out what's wrong there.
