### ISSUE TITLE
How to ignore <a> fragments?

### ISSUE THREAD

**Issue by tyteen4a03** [pateketrueke/yrv#43]
How do I instruct yrv to ignore anchor fragments?

**Comment by pateketrueke** [comment]
I don't get you, can you provide an example? Thank you!

**Comment by tyteen4a03** [comment]
`<a id="top">` and clicking on `<a href="#top">` does not work since yrv takes over trying to route it when it should be going to the `#top`.

**Comment by pateketrueke** [comment]
Oh gotcha! Do you think is fine to ignore all anchors except those starting with `#/` instead? 🤔

**Comment by tyteen4a03** [comment]
Maybe have it configurable so that when using the history API it ignores all fragments.

I don't plan on using hash and not allowing `/` is *technically* breaking the rules but eh.

**Comment by tyteen4a03** [comment]
Any progress on this issue? :)

**Comment by pateketrueke** [comment]
Hi, the only way I found to detect these kind of events is through `e.isTrusted` — so, when true seems to be from regular anchor elements.

Otherwise I'm not able to found a way to differentiate because `e` does not include the element that originated the navigation change.

What do you think?

**Comment by sjml** [comment]
Coming back at this from a different angle -- it would be very nice to be able to just put a piece of data on an anchor tag so that yrv knows not to try and route with it. In my instance, I have an SPA *except* for links starting with `/api/`; with other routers I can just flag those links to be ignored, but I can't see a way around it with yrv. 

(Apologies for resurrecting this issue; I can open a new one if you'd prefer.)

**Comment by pateketrueke** [comment]
I think a new issue would git better, if I understood, we could add a particular attribute on those links we want to ignore, right?
