### ISSUE TITLE
Conditionals are broken on Routes

### ISSUE THREAD

**Issue by r3ndd** [pateketrueke/yrv#85]
The following does not stop a Route from being rendered:

```js
<Route condition={() => false}>
</Route>
```

**Comment by pateketrueke** [comment]
Hi, can you expand more? If you have a REPL repro it would help to address this bug, thank you!

**Comment by pateketrueke** [comment]
I was looking at the code and I think is a documentation issue, the `condition` prop on `Route` works only if `redirect` is used too, that would condition if the redirect happens or not: when condition resolves to anything _truthy_, then the redirect is omitted and the route gets rendered, otherwise you are redirected.

**Comment by r3ndd** [comment]
Okay, if that's intended behavior then I'll close this issue.
